//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Ent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщики()
        {
            this.ПриходнаяНакладная = new HashSet<ПриходнаяНакладная>();
        }
    
        public int Номер { get; set; }
        public string Название { get; set; }
        public string ИННКПП { get; set; }
        public string Tелефон { get; set; }
        public string Email { get; set; }
        public int Адрес { get; set; }
    
        public virtual Адрес Адрес1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриходнаяНакладная> ПриходнаяНакладная { get; set; }
    }
}
