//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Ent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склад()
        {
            this.ТоварНаСкладе = new HashSet<ТоварНаСкладе>();
        }
    
        public int Номер { get; set; }
        public string НазваниеСклада { get; set; }
        public int Адрес { get; set; }
        public int ТипСклада { get; set; }
        public Nullable<int> ЗоныХранения { get; set; }
    
        public virtual Адрес Адрес1 { get; set; }
        public virtual ЗоныХранения ЗоныХранения1 { get; set; }
        public virtual ТипCклад ТипCклад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварНаСкладе> ТоварНаСкладе { get; set; }
    }
}
