//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public int Номер { get; set; }
        public string Название { get; set; }
        public string Tелефон { get; set; }
        public string Email { get; set; }
        public int Адрес { get; set; }

		public string ОтображаемоеИмя => $"{Название} | {Tелефон} | {Email}";

		public virtual Адрес Адрес1 { get; set; }
    }
}
