//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТоварВНакладной
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТоварВНакладной()
        {
            this.ПриходнаяНакладная = new HashSet<ПриходнаяНакладная>();
            this.РасходнаяНакладная = new HashSet<РасходнаяНакладная>();
        }
    
        public int Номер { get; set; }
        public int НомерТовара { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриходнаяНакладная> ПриходнаяНакладная { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РасходнаяНакладная> РасходнаяНакладная { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
