//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТоварНаСкладе
    {
        public int НомерЗаписи { get; set; }
        public int НомерТовара { get; set; }
        public int НомерСклада { get; set; }
        public int Количество { get; set; }
    
        public virtual Склад Склад { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
